# Generated by Django 3.0.5 on 2021-07-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='time',
        ),
    ]
