# Generated by Django 3.0.5 on 2021-07-13 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 13, 13, 5, 27, 805758, tzinfo=utc)),
        ),
    ]
