# Generated by Django 3.0.5 on 2021-07-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_work_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='time',
        ),
    ]
