# Generated by Django 3.0.5 on 2021-07-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time',
            field=models.TimeField(),
        ),
    ]
